import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { chromium, expect } from "@playwright/test";
import { checkPlayerRail } from "./player-rail-browser.ts";
import { checkLayout } from "./layout-browser.ts";
import { checkChrome } from "./chrome-browser.ts";
import { checkBrand } from "./brand-browser.ts";
import { checkFooterMotion } from "./footer-motion-browser.ts";
import { installShaderProbe } from "./shader-probe.ts";
import { checkComponents } from "./components-browser.ts";
import { checkEcosystem } from "./ecosystem-browser.ts";
import { checkChartControls } from "./chart-controls-browser.ts";

const url = process.env.FLINCH_UI_URL ?? "http://127.0.0.1:3000/play";
assert.equal(new URL(url).hostname, "127.0.0.1", "UI checks only run against loopback");
const directory = resolve(`artifacts/runs/ui-smoke-${Date.now()}`);
mkdirSync(directory, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.FLINCH_BROWSER_EXECUTABLE });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors: string[] = [];
page.on("pageerror", error => errors.push(error.message));
page.setDefaultTimeout(20_000);
await installShaderProbe(page);

try {
  await page.goto(url);
  await expect(page.getByRole("button", { name: "Create room", exact: true })).toBeDisabled();
  await expect(page.getByRole("region", { name: "Transaction activity" })).toHaveCount(0);
  assert.equal(await page.locator(".status-dot, .seat-avatar, .sol-mark").count(), 0);
  await expect(page.getByText("Live reference", { exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText("Reference only · not your sell price")).toBeVisible();
  assert.equal(await page.locator(".feed-status").evaluate(element => getComputedStyle(element, "::before").content), "none");
  const chrome = await checkChrome(page, directory);
  const components = await checkComponents(page, directory);
  const brand = await checkBrand(page, directory);
  const ecosystem = await checkEcosystem(page, directory);
  const chartInteraction = await checkChartControls(page);
  const footerMotion = await checkFooterMotion(page, browser, url, directory);
  const playerRail = await checkPlayerRail(page, browser, url, directory);
  await page.getByRole("combobox", { name: "Chart style", exact: true }).selectOption("line");
  await expect(page.getByRole("combobox", { name: "Chart style", exact: true })).toHaveValue("line");
  await page.getByRole("button", { name: "5m", exact: true }).click();
  await expect(page.getByRole("button", { name: "5m", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Reset chart view", exact: true }).click();
  await page.getByRole("button", { name: "0.005 SOL", exact: true }).click();
  await expect(page.getByLabel("Stake per player, in SOL")).toHaveValue("0.005");
  await page.getByRole("button", { name: "Have a room code?", exact: true }).click();
  await page.getByLabel("Room address or invite link", { exact: true }).fill("invalid-room");
  await page.getByRole("button", { name: "Open room", exact: true }).click();
  await expect(page.locator('[data-sonner-toast][data-type="warning"]').filter({ hasText: "Check the room link" })).toBeVisible();
  await expect(page.getByLabel("Room address or invite link", { exact: true })).toBeFocused();
  await page.getByRole("button", { name: "How to play", exact: true }).click();
  await expect(page.locator("#navigation-rules")).toHaveCSS("opacity", "1");
  await expect(page.getByRole("button", { name: "How to play", exact: true })).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(page.getByRole("button", { name: "Protocol", exact: true })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "How to play", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.locator("#navigation-rules")).toHaveAttribute("inert", "");
  await expect(page.getByRole("button", { name: "How to play", exact: true })).toBeFocused();
  await page.getByRole("combobox", { name: "Chart style", exact: true }).selectOption("candles");
  await page.getByRole("button", { name: "1m", exact: true }).click();
  await page.reload();
  await expect(page.getByText("Live reference", { exact: true })).toBeVisible({ timeout: 20_000 });
  const layout = await checkLayout(page, directory);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.getByRole("button", { name: "Open menu", exact: true }).click();
  await page.getByRole("button", { name: "How to play", exact: true }).click();
  await expect(page.locator("#navigation-rules")).toHaveCSS("opacity", "1");
  await expect(page.locator("#navigation-rules")).toHaveCSS("transform", "none");
  await page.keyboard.press("Escape");
  await page.context().setOffline(true);
  await expect(page.getByText("Offline. New transactions are paused. Submitted transactions may still complete.")).toBeVisible();
  await page.context().setOffline(false);
  await expect(page.getByText("Live reference", { exact: true })).toBeVisible({ timeout: 20_000 });
  await page.route("**/api/market", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Test outage" }) }));
  await page.reload();
  await expect(page.getByText("Reference feed unavailable", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Have a room code?", exact: true }).click();
  await expect(page.getByRole("button", { name: "Open room", exact: true })).toBeEnabled();
  assert.deepEqual(errors, []);
  writeFileSync(resolve(directory, "result.json"), JSON.stringify({ complete: true, readOnly: true, liveCoinbaseFeed: true, layout, playerRail, chrome, components, brand, ecosystem, footerMotion, chartInteraction, chartControls: true, rulesNavigationKeyboard: true, offlineRecovery: true, explicitFeedOutage: true, pageErrors: errors }, null, 2));
  console.log(`UI smoke passed: ${directory}`);
} catch (error) {
  await page.screenshot({ path: resolve(directory, "failure.png"), fullPage: true });
  console.error(`UI evidence: ${directory}`);
  console.error(await page.evaluate(() => [...document.querySelectorAll<HTMLElement>("body *")]
    .filter(element => element.getBoundingClientRect().right > innerWidth && element.getClientRects().length > 0)
    .map(element => ({ tag: element.tagName, className: element.getAttribute("class"), right: element.getBoundingClientRect().right })).slice(0, 20)));
  throw error;
} finally { await browser.close(); }
